---
output: html_document
title: "Conjunction Pure Cluster Analysis"
---

```{r include=F}
knitr::opts_chunk$set(echo=F)
knitr::opts_chunk$set(warning=F)
knitr::opts_chunk$set(message=F)
print("In Conjuntion_pure_cluster/pure_cumnum.Rmd")

user_website <- file.path(path.expand('~'), "Website", "WebsiteFiles")
print(paste("user_website", user_website))

if(!require(tidyverse)) {install.packages("tidyverse", repos="https://cran.us.r-project.org")}
if(!require(kableExtra)) {install.packages("kableExtra", repos="https://cran.us.r-project.org")}
if(!require(DT)) {install.packages("DT", repos="https://cran.us.r-project.org")}

library(tidyverse)
library(readr)
library(kableExtra)
library(knitr)
library(lubridate)
library(DT)
library(RColorBrewer)
library(stringr)
library(scales)

Sys.setenv(TZ='EST')

mcma_objs = readRDS(file.path(user_website, "RDSfiles", "mcma_objs"))
all_conjs_pure = readRDS(file.path(user_website, "pureRDSfiles", "all_conjs_pure"))
derelicts = readRDS(file.path(user_website, "RDSfiles", "derelicts")) 
derelictDat = readRDS(file.path(user_website, "RDSfiles", "derelictDatNew"))
alt_bins = readRDS(file.path(user_website, "RDSfiles", "alt_bins"))
file_list_pure = readRDS(file.path(user_website, "RDSfiles", "file_list_pure"))

today = toupper(strftime(Sys.Date(), format="%d%b%Y")) # current day
```

```{r update_conj_files, warning=F}
```

## Miss distance vs cumulative count plot
```{r miss_dist_cum_count_plot}
mycolors = c(brewer.pal(name="Set1", n = 9), brewer.pal(name="Set2", n = 4))
mycolors[6] = "#000000"

all_conjs_pure %>%
  mutate(Range = Range * 1000) %>%
  group_by(clusterLab_pure) %>%
  arrange(Range) %>%
  mutate(rowid = 1, cumnum = cumsum(rowid)) %>% 
  rename(Clusters = clusterLab_pure) %>% 
  ggplot(aes(x=Range, y = cumnum, color=Clusters, linetype=Clusters)) +
  geom_line()+
  theme_light() +
  scale_x_log10(labels = c(10,100,500,1000,5000), 
                breaks = c(10,100,500,1000,5000))+
  
  scale_y_log10(labels = c(10,100,300,500,1000,3000,5000), 
                breaks = c(10,100,300,500,1000,3000,5000)) +
  labs(x="Miss Distance (m)", y="Cumulative Number of Encounters",
       title="Cumulative Number of Encounters by Cluster", 
       subtitle = paste0("Encounters from 31MAR2016-",today))+
  scale_color_manual(values = mycolors)+
  annotation_logticks()+
  scale_linetype_manual(values=c("dashed", "solid", "solid", "solid",
                                 "solid", "solid", "solid", "solid", "solid", "dashed"))

```







